FROM python:3.12-slim

RUN apt-get update && apt-get install -y git gcc cron poppler-utils tesseract-ocr tesseract-ocr-spa tesseract-ocr-cat antiword

COPY requirements.txt /app/
WORKDIR /app
RUN pip install -r requirements.txt

RUN touch /var/log/cron.log

CMD tail -f /var/log/cron.log
